"""added tags to post table

Revision ID: 6e87ed8f5c93
Revises: e394b9ab0a8d
Create Date: 2025-06-08 14:34:33.148484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e87ed8f5c93'
down_revision = 'e394b9ab0a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
