"""slugify post

Revision ID: e10c731fd815
Revises: 01d79c47cc24
Create Date: 2025-05-28 23:15:47.005790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10c731fd815'
down_revision = '01d79c47cc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=128), nullable=False))
        batch_op.create_index(batch_op.f('ix_post_slug'), ['slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
